# Generated by Django 5.1.1 on 2024-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
